safe-global/safe-events-service

.dockerignore
.github/workflows/ci.yml
Dockerfile

- Add docker build to Github actions task

Add Dockerfile

---

.env.sample
src/datasources/db/database.provider.ts

Use URL configuration for Postgresql

---

README.md
package-lock.json
package.json
src/app.module.ts
src/datasources/queue/queue.health.ts
src/datasources/queue/queue.module.ts
src/datasources/queue/queue.provider.spec.ts
src/datasources/queue/queue.provider.ts
src/health/health.controller.spec.ts
src/health/health.controller.ts
src/health/health.module.ts
test/events.e2e-spec.ts

Add /health endpoint

---

.env.docker
.github/workflows/ci.yml
Dockerfile
README.md
docker-compose.yml
scripts/db_check_migrations.sh
scripts/db_config.sh
scripts/db_generate_migrations.sh
scripts/db_run_migrations.sh
scripts/db_run_migrations_production.sh
scripts/docker_run.sh
src/datasources/db/database.options.ts
src/datasources/db/database.provider.ts
src/datasources/db/ormconfig.ts
src/datasources/migrations/1687183474366-initial.ts

- Add scripts to generate/run migrations
- Add entrypoint script for docker image
- Add initial migration
- Refactor TypeORM configuration so TypeORM cli can use it
- Add instructions on Dockerfile
- Add new .env.docker to use with docker compose

Add database migrations

---

src/app.module.ts
src/logging/json-logger.spec.ts
src/logging/json-logger.ts
src/main.ts

Logs will follow this structure on production mode:
```
{"timestamp":"2023-06-21T12:35:23.939Z","context":"InstanceLoader","level":"log","message":"AppModule dependencies initialized"}
{"timestamp":"2023-06-21T12:35:23.939Z","context":"InstanceLoader","level":"log","message":"DatabaseModule dependencies initialized"}
{"timestamp":"2023-06-21T12:35:23.939Z","context":"InstanceLoader","level":"log","message":"TypeOrmModule dependencies initialized"}
{"timestamp":"2023-06-21T12:35:23.939Z","context":"InstanceLoader","level":"log","message":"CacheModule dependencies initialized"}
{"timestamp":"2023-06-21T12:35:23.940Z","context":"InstanceLoader","level":"log","message":"ConfigHostModule dependencies initialized"}
{"timestamp":"2023-06-21T12:35:23.940Z","context":"InstanceLoader","level":"log", …
```

Log JSON in production mode

---

src/datasources/queue/queue.provider.ts
src/routes/webhook/webhook.module.ts
src/routes/webhook/webhook.service.spec.ts

- Prefetch messages from queue, not more than prefetch messages can be processed at the same time
- Add timeouts for Axios and don't allow http redirects

Optimize message processing

---

README.md
docker-compose.yml
scripts/run_tests.sh
src/datasources/queue/queue.provider.ts
test/events.e2e-spec.ts
test/util.ts

- Create util package for 2e2 tests
- Fix error for postgres healthcheck
- Use YAML anchors for docker-compose
- Add run_tests.sh script

Organize code

---

src/datasources/migrations/1689597925334-webhook-authorization.ts
src/routes/webhook/entities/webhook.entity.ts
src/routes/webhook/webhook.service.spec.ts
src/routes/webhook/webhook.service.ts
test/events.e2e-spec.ts

Add basic auth support for webhooks

---

.env.sample
src/admin/adminjs.ts
src/main.ts

- Add globalprefix to nest configuration
- Add basePath to swagger url
- Add basePath to adminjs
Closes #92

Add URL_BASE_PATH environment variable

---

package-lock.json
package.json

Set version 0.5.0

---

package-lock.json
package.json
src/routes/events/events.controller.ts

- https://viem.sh/docs/introduction.html#performance

Replace ethers by viem

---

README.md
src/routes/events/event.dto.ts
src/routes/webhook/entities/webhook.entity.spec.ts
src/routes/webhook/entities/webhook.entity.ts

- Depends on https://github.com/safe-global/safe-transaction-service/pull/1810

Add DELETED_MULTISIG_TRANSACTION event

---

README.md

closes https://github.com/safe-global/safe-events-service/issues/117

Add OUTGOING_ETHER event to readme

---

src/routes/webhook/webhook.service.ts

- Log request errors, response errors or response not received errors

Improve http requests logging

---

src/routes/webhook/webhook.service.spec.ts

closes https://github.com/safe-global/safe-events-service/issues/151

Add test for Axios errors

---

package-lock.json
package.json

- Found the solution on https://github.com/nestjs/swagger/issues/2849

Rollback typeorm to v0.3.19

---

Dockerfile

- Revert after https://github.com/npm/cli/issues/4828 is implemented

Implement workaround for npm issue

---

src/datasources/db/database.provider.ts

- It should speed up application loading
- https://docs.nestjs.com/fundamentals/async-providers

Create async datasource

---

README.md
package.json
src/routes/webhook/webhook.service.spec.ts
src/routes/webhook/webhook.service.ts

Closes https://github.com/safe-global/safe-events-service/issues/206

Add debug log  for valid webhook request

---

README.md
src/datasources/migrations/1729516032564-SendReorgs.ts
src/routes/events/event.dto.ts
src/routes/webhook/entities/webhook.entity.spec.ts
src/routes/webhook/entities/webhook.entity.ts

Add support for reorg events

---

README.md
src/datasources/migrations/1730984672394-SendDelegates.ts
src/routes/events/event.dto.ts
src/routes/webhook/entities/webhook.entity.spec.ts
src/routes/webhook/entities/webhook.entity.ts

Add support for delegates events

---

README.md

- Related with https://github.com/safe-global/safe-transaction-service/issues/2377

Add "to" field to PENDING and EXECUTED multisig tx

---

.github/workflows/ci.yml
Dockerfile
README.md
docker-compose.yml

- setup postgres 16 on docker compose and github flow

Bump to node v22 and setup postgres 16
